slam_toolbox:
  ros__parameters:
    # General Parameters
    use_sim_time: true
    map_frame: map
    odom_frame: odom
    base_frame: base_footprint

    # Scan matching parameters
    mode: mapping # mapping or localization
    max_laser_range: 10.0
    map_start_pose: [0.0, 0.0, 0.0]
    map_update_interval: 5.0
    resolution: 0.05
    max_submap_size: 20.0

    # Loop closure parameters
    enable_interactive_mode: false
    loop_closure_enabled: true
    minimumTravelDistance: 0.5
    minimumTravelHeading: 0.5
    
    # Optimization parameters
    optimizer_params:
      enable_interactive_mode: false
      
    # Debug
    debug_logging: false
    throttle_scans: 1
