slam_toolbox:
  ros__parameters:
    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: scan
    mode: mapping # Can be mapping, localization, or offline
    use_sim_time: true
    
    # General SLAM Parameters
    map_update_interval: 1.0
    resolution: 0.05
    max_laser_range: 10.0
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    
    # Loop Closure Parameters
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_covariance: 1.0
    
    # Scan Matcher Parameters
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349 # ~0.2 degrees
    coarse_search_angle_offset: 0.0349 # ~2 degrees
    fine_search_angle_resolution: 0.00175 # ~0.1 degrees
    coarse_angle_resolution: 0.0175 # ~1.0 degrees
    
    # Motion model parameters
    motion_model_alpha1: 0.1
    motion_model_alpha2: 0.1
    motion_model_alpha3: 0.1
    motion_model_alpha4: 0.1
    motion_model_alpha5: 0.1 